### ISSUE TITLE
Download and Install Android Studio and Understand How to Use it. - Ed

### ISSUE THREAD

**Issue by forrest87** [CiderCS3398/CS3398-Cider-S2017#15]
Ed will familiarize himself with Android Studio and run a simple Hello World program on the emulator.

**Comment by ejd30** [comment]
I have learned by watching others use Android Studio. I still need to practice using Version Control to commit changes to github.

**Comment by ejd30** [comment]
![android studio](https://cloud.githubusercontent.com/assets/25306491/23494082/0de38210-fed6-11e6-862c-157a66a9aeed.JPG)
I've gotten the emulator running on my computer.
