### ISSUE TITLE
As a developer, I would like to plan how our database tables will be set up. - Sherman

### ISSUE THREAD

**Issue by stt19** [CiderCS3398/CS3398-Cider-S2017#23]
Ideally, the tables would be setup in a way that makes things efficient when the application interacts with it.

**Comment by stt19** [comment]
Eddie and I collaborated on this after class on Wednesday. We wrote out some basic diagrams to plan for how we would set up the database once it got up and running. Eddie seemed to already have a good idea of how the layout would work, because he has taken the Databases course here already. I worked to make sure that I understood the relationships between tables that he proposed, along with how we might think about implementing it.

**Comment by drlehr** [comment]
Do you have the diagrams?

**Comment by stt19** [comment]
![data_pic](https://cloud.githubusercontent.com/assets/25232677/23243841/1fed031c-f947-11e6-9be1-5dbe9c376f47.jpeg)
![diagram2](https://cloud.githubusercontent.com/assets/25232677/23243904/847b8498-f947-11e6-8d6a-c4f4864cdcde.jpeg)
![diagram3](https://cloud.githubusercontent.com/assets/25232677/23243906/86b383b4-f947-11e6-8dcb-56730240333b.jpeg)
