### ISSUE TITLE
Research Base Recipes to enter into App. - Christian

### ISSUE THREAD

**Issue by forrest87** [CiderCS3398/CS3398-Cider-S2017#27]
Locate and collect very basic and common recipes on the web that can be used as recipes for the application.

**Comment by sylchristian** [comment]
I have altered the time estimate for this task, since there is now a possibility that we will be using external sources for recipes to populate our database, and it will thus be less important to spend time compiling various recipes by hand.

**Comment by sylchristian** [comment]
I will be moving this issue to the release backlog as there is not much point in researching recipes to put into a database that is not yet ready. Figuring out how and where recipes for the app will come from would be a good task for the second sprint.

**Comment by sylchristian** [comment]
I will be closing this issue, as it is no longer relevant to developing our app. We can easily insert a few recipes into either our database once it is constructed or we can add the recipes to the .json file in the project as we need them.
