### ISSUE TITLE
Enter Recipe1 into Database.

### ISSUE THREAD

**Issue by forrest87** [CiderCS3398/CS3398-Cider-S2017#29]
The collection of initial recipes will be passed on to the database developers to input recipes into the database.

**Comment by ejd30** [comment]
I moved this out of Sprint 1 since the Database itself is taking longer than Expected.

**Comment by ejd30** [comment]
![recipe1](https://cloud.githubusercontent.com/assets/25306491/24688300/b9e92402-1984-11e7-8c3a-34c042c893bb.JPG)
